import p1 from "./Media/all-item-pics/product1.jpg";
import p2 from "./Media/all-item-pics/product2.jpg";




const Allproducts = [
    {
      id: 1,
      title: "Wireless Bluetooth Earbuds",
      category: "Electronics",
      price: 39.99,
      instock: true,
      img: {p1},
      description: "Experience the ultimate freedom with our Wireless Bluetooth Earbuds. These earbuds offer crystal clear sound quality and come with a charging case for on-the-go convenience. Stay connected without the hassle of wires.",
    },
    {
      id: 2,
      title: "Men's Classic Leather Wallet",
      category: "Fashion",
      price: 29.99,
      instock: true,
      img: {p2},
      description: "Elevate your style with our Men's Classic Leather Wallet. Crafted from premium leather, this wallet features multiple card slots, a bill compartment, and a sleek design. Keep your essentials organized in style.",
    },
    {
      id: 3,
      title: "Smart Home Security Camera",
      category: "Home & Kitchen",
      price: 49.99,
      instock: true,
      img: "path/to/product3.jpg",
      description: "Protect your home with our Smart Home Security Camera. With advanced motion detection and night vision capabilities, you can monitor your home from anywhere. Stay connected and keep your loved ones safe.",
    },
    {
      id: 4,
      title: "Women's Running Shoes",
      category: "Sports & Outdoors",
      price: 59.99,
      instock: true,
      img: "path/to/product4.jpg",
      description: "Run with confidence in our Women's Running Shoes. Designed for maximum comfort and performance, these shoes feature lightweight construction, responsive cushioning, and a stylish design. Take your runs to the next level.",
    },
    {
      id: 5,
      title: "Portable External Battery Pack",
      category: "Electronics",
      price: 24.99,
      instock: true,
      img: "path/to/product5.jpg",
      description: "Stay powered up on the go with our Portable External Battery Pack. This compact and lightweight battery pack provides fast charging for your devices, ensuring you never run out of battery when you need it most. Perfect for travel and outdoor activities.",
    },
    {
      id: 6,
      title: "Stainless Steel Water Bottle",
      category: "Home & Kitchen",
      price: 19.99,
      instock: true,
      img: "path/to/product6.jpg",
      description: "Stay hydrated in style with our Stainless Steel Water Bottle. Made from high-quality stainless steel, this water bottle is durable, eco-friendly, and leak-proof. Keep your drinks cold or hot for hours wherever you go.",
    },
    {
      id: 7,
      title: "Digital Alarm Clock",
      category: "Home & Kitchen",
      price: 12.99,
      instock: true,
      img: "path/to/product7.jpg",
      description: "Wake up refreshed with our Digital Alarm Clock. Featuring a large LED display, multiple alarm settings, and snooze function, this alarm clock ensures you never oversleep again. Start your day on time and in style.",
    },
    {
      id: 8,
      title: "Wireless Gaming Mouse",
      category: "Electronics",
      price: 34.99,
      instock: true,
      img: "path/to/product8.jpg",
      description: "Dominate the battlefield with our Wireless Gaming Mouse. Engineered for precision and comfort, this mouse features customizable RGB lighting, programmable buttons, and ultra-fast response time. Gain the competitive edge and victory will be yours.",
    },
    {
      id: 9,
      title: "Compact Foldable Travel Backpack",
      category: "Travel & Accessories",
      price: 39.99,
      instock: true,
      img: "path/to/product9.jpg",
      description: "Travel with ease and convenience with our Compact Foldable Travel Backpack. This versatile backpack folds into a compact size for easy storage and expands into a spacious backpack when needed. Perfect for travelers, commuters, and adventurers.",
    },
    {
      id: 10,
      title: "Aviator Sunglasses",
      category: "Fashion",
      price: 19.99,
      instock: true,
      img: "path/to/product10.jpg",
      description: "Stay stylish and protected from the sun with our Aviator Sunglasses. Featuring classic aviator style and UV protection, these sunglasses are perfect for both casual and outdoor activities. Elevate your look and shield your eyes from harmful UV rays.",
    },

    {
        id: 11,
        title: "Portable Mini Bluetooth Speaker",
        category: "Electronics",
        price: 29.99,
        instock: true,
        img: "path/to/product11.jpg",
        description: "Bring the party with you wherever you go with our Portable Mini Bluetooth Speaker. This compact speaker delivers powerful sound with enhanced bass, making it perfect for music lovers on the move. Enjoy your favorite tunes anytime, anywhere.",
      },
      {
        id: 12,
        title: "Men's Casual Cotton T-Shirt",
        category: "Fashion",
        price: 14.99,
        instock: true,
        img: "path/to/product12.jpg",
        description: "Upgrade your casual wardrobe with our Men's Casual Cotton T-Shirt. Made from soft and breathable cotton fabric, this t-shirt features a stylish graphic print and comfortable fit. Pair it with your favorite jeans for a laid-back look.",
      },
      {
        id: 13,
        title: "Compact Folding Pocket Knife",
        category: "Tools & Home Improvement",
        price: 24.99,
        instock: true,
        img: "path/to/product13.jpg",
        description: "Be prepared for any situation with our Compact Folding Pocket Knife. Constructed with a durable stainless steel blade and ergonomic handle, this knife is perfect for everyday carry, camping, hiking, and more. Stay sharp and ready for adventure.",
      },
      {
        id: 14,
        title: "Insulated Stainless Steel Travel Mug",
        category: "Home & Kitchen",
        price: 19.99,
        instock: true,
        img: "path/to/product14.jpg",
        description: "Keep your drinks hot or cold on the go with our Insulated Stainless Steel Travel Mug. Featuring double-wall insulation and a convenient flip lid, this travel mug is perfect for commuting, traveling, and outdoor activities. Say goodbye to lukewarm drinks.",
      },
      {
        id: 15,
        title: "Fitness Tracker Watch",
        category: "Sports & Outdoors",
        price: 59.99,
        instock: true,
        img: "path/to/product15.jpg",
        description: "Track your fitness goals with our Fitness Tracker Watch. With built-in heart rate monitor, GPS, and activity tracking features, this watch helps you stay motivated and on track with your workouts. Monitor your progress and achieve your best results.",
      },
      {
        id: 16,
        title: "Professional Hair Dryer",
        category: "Beauty & Personal Care",
        price: 39.99,
        instock: true,
        img: "path/to/product16.jpg",
        description: "Achieve salon-quality results at home with our Professional Hair Dryer. This powerful hair dryer features multiple heat and speed settings, as well as a concentrator nozzle for precise styling. Say goodbye to frizz and hello to smooth, shiny hair.",
      },
      {
        id: 17,
        title: "Gaming Keyboard and Mouse Combo",
        category: "Electronics",
        price: 49.99,
        instock: true,
        img: "path/to/product17.jpg",
        description: "Level up your gaming experience with our Gaming Keyboard and Mouse Combo. Featuring customizable RGB lighting and ergonomic design, this combo delivers precision and comfort for extended gaming sessions. Dominate the battlefield with ease.",
      },
      {
        id: 18,
        title: "Set of Stainless Steel Mixing Bowls",
        category: "Home & Kitchen",
        price: 29.99,
        instock: true,
        img: "path/to/product18.jpg",
        description: "Upgrade your kitchen essentials with our Set of Stainless Steel Mixing Bowls. Perfect for baking, cooking, and food preparation, these durable mixing bowls come in various sizes to suit all your kitchen needs. Say goodbye to flimsy plastic bowls and hello to reliable stainless steel.",
      },
      {
        id: 19,
        title: "Men's Waterproof Hiking Boots",
        category: "Sports & Outdoors",
        price: 79.99,
        instock: true,
        img: "path/to/product19.jpg",
        description: "Conquer the trails with our Men's Waterproof Hiking Boots. Built to withstand rugged terrain and harsh weather conditions, these boots offer superior traction, support, and durability. Stay comfortable and confident on your outdoor adventures.",
      },
      {
        id: 20,
        title: "Reusable Silicone Food Storage Bags",
        category: "Home & Kitchen",
        price: 14.99,
        instock: true,
        img: "path/to/product20.jpg",
        description: "Go green with our Reusable Silicone Food Storage Bags. Made from premium food-grade silicone, these eco-friendly bags are perfect for storing leftovers, snacks, and meal prep. Say goodbye to single-use plastic bags and reduce your carbon footprint.",
      },{
      id: 20,
      title: "Elegant Rose Gold Women's Watch",
      category: "Fashion",
      price: 69.99,
      instock: true,
      img: "path/to/product20.jpg",
      description: "Add a touch of luxury to your wrist with our Elegant Rose Gold Women's Watch. Featuring a sleek design and shimmering rose gold finish, this watch is perfect for both casual and formal occasions. Stay stylish and punctual with this timeless timepiece.",
    },
    {
      id: 21,
      title: "Portable Mini Bluetooth Speaker",
      category: "Electronics",
      price: 29.99,
      instock: true,
      img: "path/to/product21.jpg",
      description: "Bring the party with you wherever you go with our Portable Mini Bluetooth Speaker. This compact speaker delivers powerful sound with enhanced bass, making it perfect for music lovers on the move. Enjoy your favorite tunes anytime, anywhere.",
    },
    {
      id: 22,
      title: "Smart Home Security Camera",
      category: "Home & Kitchen",
      price: 49.99,
      instock: true,
      img: "path/to/product22.jpg",
      description: "Protect your home with our Smart Home Security Camera. With advanced motion detection and night vision capabilities, you can monitor your home from anywhere. Stay connected and keep your loved ones safe.",
    },
    {
      id: 23,
      title: "Men's Casual Canvas Sneakers",
      category: "Fashion",
      price: 34.99,
      instock: true,
      img: "path/to/product23.jpg",
      description: "Step up your casual style with our Men's Casual Canvas Sneakers. These versatile sneakers feature a classic design, durable canvas upper, and comfortable fit. Pair them with jeans or shorts for a laid-back look that never goes out of style.",
    },
    {
      id: 24,
      title: "Reusable Silicone Food Storage Bags",
      category: "Home & Kitchen",
      price: 14.99,
      instock: true,
      img: "path/to/product24.jpg",
      description: "Go green with our Reusable Silicone Food Storage Bags. Made from premium food-grade silicone, these eco-friendly bags are perfect for storing leftovers, snacks, and meal prep. Say goodbye to single-use plastic bags and reduce your carbon footprint.",
    },
    {
      id: 25,
      title: "Fitness Tracker Watch",
      category: "Sports & Outdoors",
      price: 59.99,
      instock: true,
      img: "path/to/product25.jpg",
      description: "Track your fitness goals with our Fitness Tracker Watch. With built-in heart rate monitor, GPS, and activity tracking features, this watch helps you stay motivated and on track with your workouts. Monitor your progress and achieve your best results.",
    },
    {
      id: 26,
      title: "Insulated Stainless Steel Travel Mug",
      category: "Home & Kitchen",
      price: 19.99,
      instock: true,
      img: "path/to/product26.jpg",
      description: "Keep your drinks hot or cold on the go with our Insulated Stainless Steel Travel Mug. Featuring double-wall insulation and a convenient flip lid, this travel mug is perfect for commuting, traveling, and outdoor activities. Say goodbye to lukewarm drinks.",
    },
    {
      id: 27,
      title: "Compact Foldable Travel Backpack",
      category: "Travel & Accessories",
      price: 39.99,
      instock: true,
      img: "path/to/product27.jpg",
      description: "Travel with ease and convenience with our Compact Foldable Travel Backpack. This versatile backpack folds into a compact size for easy storage and expands into a spacious backpack when needed. Perfect for travelers, commuters, and adventurers.",
    },
    {
      id: 28,
      title: "Classic Aviator Sunglasses",
      category: "Fashion",
      price: 19.99,
      instock: true,
      img: "path/to/product28.jpg",
      description: "Stay stylish and protected from the sun with our Classic Aviator Sunglasses. Featuring polarized lenses and timeless design, these sunglasses offer superior clarity and glare reduction. Perfect for outdoor activities and everyday wear.",
    },
    {
      id: 29,
      title: "Ultra-Portable External Battery Pack",
      category: "Electronics",
      price: 39.99,
      instock: true,
      img: "path/to/product29.jpg",
      description: "Never run out of battery on your adventures with our Ultra-Portable External Battery Pack. Compact and lightweight, this battery pack provides fast charging for your devices, making it the perfect travel companion. Stay powered up wherever you go!",
    },
    {
      id: 30,
      title: "Men's Waterproof Hiking Boots",
      category: "Sports & Outdoors",
      price: 79.99,
      instock: true,
      img: "path/to/product30.jpg",
      description: "Conquer the trails with our Men's Waterproof Hiking Boots. Built to withstand rugged terrain and harsh weather conditions, these boots offer superior traction, support, and durability. Stay comfortable and confident on your outdoor adventures.",
    },
    {
        id: 30,
        title: "Men's Waterproof Hiking Boots",
        category: "Sports & Outdoors",
        price: 79.99,
        instock: true,
        img: "path/to/product30.jpg",
        description: "Conquer the trails with our Men's Waterproof Hiking Boots. Built to withstand rugged terrain and harsh weather conditions, these boots offer superior traction, support, and durability. Stay comfortable and confident on your outdoor adventures.",
      },
      {
        id: 31,
        title: "Portable Espresso Maker",
        category: "Home & Kitchen",
        price: 49.99,
        instock: true,
        img: "path/to/product31.jpg",
        description: "Enjoy delicious espresso on the go with our Portable Espresso Maker. This compact and lightweight espresso maker allows you to brew your favorite coffee wherever you are. Perfect for camping, travel, and outdoor adventures.",
      },
      {
        id: 32,
        title: "Wireless Noise-Canceling Headphones",
        category: "Electronics",
        price: 129.99,
        instock: true,
        img: "path/to/product32.jpg",
        description: "Immerse yourself in music with our Wireless Noise-Canceling Headphones. Featuring advanced noise-canceling technology and superior sound quality, these headphones deliver an unparalleled listening experience. Block out distractions and enjoy your music in peace.",
      },
      {
        id: 33,
        title: "Women's Yoga Leggings",
        category: "Sports & Outdoors",
        price: 39.99,
        instock: true,
        img: "path/to/product33.jpg",
        description: "Find your flow in our Women's Yoga Leggings. Made from stretchy and breathable fabric, these leggings offer comfort and support for your yoga practice. With a high-waisted design and moisture-wicking properties, they keep you comfortable and focused.",
      },
      {
        id: 34,
        title: "Stainless Steel Water Bottle",
        category: "Home & Kitchen",
        price: 19.99,
        instock: true,
        img: "path/to/product34.jpg",
        description: "Stay hydrated in style with our Stainless Steel Water Bottle. Made from high-quality stainless steel, this water bottle is durable, eco-friendly, and leak-proof. Keep your drinks cold or hot for hours wherever you go.",
      },
      {
        id: 35,
        title: "Men's Classic Leather Belt",
        category: "Fashion",
        price: 29.99,
        instock: true,
        img: "path/to/product35.jpg",
        description: "Complete your look with our Men's Classic Leather Belt. Crafted from genuine leather with a timeless buckle design, this belt adds a touch of sophistication to any outfit. Perfect for both casual and formal occasions.",
      },
      {
        id: 36,
        title: "Digital Kitchen Scale",
        category: "Home & Kitchen",
        price: 14.99,
        instock: true,
        img: "path/to/product36.jpg",
        description: "Cook with precision using our Digital Kitchen Scale. This sleek and compact scale allows you to accurately measure ingredients for your recipes. With a user-friendly interface and easy-to-read display, cooking has never been easier.",
      },
      {
        id: 37,
        title: "Wireless Charging Pad",
        category: "Electronics",
        price: 19.99,
        instock: true,
        img: "path/to/product37.jpg",
        description: "Say goodbye to tangled cables with our Wireless Charging Pad. Simply place your Qi-enabled device on the charging pad to start charging wirelessly. With fast charging capabilities and a sleek design, it's the perfect accessory for your desk or nightstand.",
      },
      {
        id: 38,
        title: "Women's Lightweight Rain Jacket",
        category: "Fashion",
        price: 49.99,
        instock: true,
        img: "path/to/product38.jpg",
        description: "Stay dry and stylish on rainy days with our Women's Lightweight Rain Jacket. Made from waterproof and breathable fabric, this jacket features a hood, adjustable cuffs, and zippered pockets. Don't let the rain dampen your style.",
      },
      {
        id: 39,
        title: "Portable Camping Lantern",
        category: "Sports & Outdoors",
        price: 24.99,
        instock: true,
        img: "path/to/product39.jpg",
        description: "Light up your campsite with our Portable Camping Lantern. With adjustable brightness levels and a compact design, this lantern is perfect for camping, hiking, and outdoor adventures. Illuminate your path and enjoy the great outdoors.",
      },
      {
        id: 40,
        title: "Compact Travel Umbrella",
        category: "Travel & Accessories",
        price: 12.99,
        instock: true,
        img: "path/to/product40.jpg",
        description: "Stay dry on the go with our Compact Travel Umbrella. This lightweight umbrella folds down to a compact size, making it perfect for travel, commuting, and everyday use. Don't let unexpected showers catch you off guard.",
      }, {
        id: 40,
        title: "Compact Travel Umbrella",
        category: "Travel & Accessories",
        price: 12.99,
        instock: true,
        img: "path/to/product40.jpg",
        description: "Stay dry on the go with our Compact Travel Umbrella. This lightweight umbrella folds down to a compact size, making it perfect for travel, commuting, and everyday use. Don't let unexpected showers catch you off guard.",
      },
      {
        id: 41,
        title: "Digital LED Alarm Clock with Sunrise Simulation",
        category: "Home & Kitchen",
        price: 29.99,
        instock: true,
        img: "path/to/product41.jpg",
        description: "Wake up refreshed with our Digital LED Alarm Clock with Sunrise Simulation. This alarm clock mimics the natural sunrise to gently wake you up, leaving you feeling energized and ready to tackle the day ahead. Say goodbye to groggy mornings.",
      },
      {
        id: 42,
        title: "Wireless Bluetooth Earbuds",
        category: "Electronics",
        price: 39.99,
        instock: true,
        img: "path/to/product42.jpg",
        description: "Cut the cord and enjoy freedom with our Wireless Bluetooth Earbuds. These earbuds offer crystal-clear sound quality, ergonomic design, and long-lasting battery life. Perfect for workouts, commuting, and everyday use.",
      },
      {
        id: 43,
        title: "Stainless Steel Mixing Bowls Set",
        category: "Home & Kitchen",
        price: 24.99,
        instock: true,
        img: "path/to/product43.jpg",
        description: "Upgrade your kitchen with our Stainless Steel Mixing Bowls Set. These durable and versatile mixing bowls are perfect for baking, cooking, and food storage. With various sizes and stackable design, they are a must-have for any kitchen.",
      },
      {
        id: 44,
        title: "Women's Quilted Puffer Jacket",
        category: "Fashion",
        price: 59.99,
        instock: true,
        img: "path/to/product44.jpg",
        description: "Stay warm and stylish in our Women's Quilted Puffer Jacket. Featuring a flattering quilted design and cozy insulation, this jacket keeps you warm during chilly days. Whether you're running errands or exploring the outdoors, stay cozy in style.",
      },
      {
        id: 45,
        title: "Smart Wi-Fi Light Bulb",
        category: "Home & Kitchen",
        price: 19.99,
        instock: true,
        img: "path/to/product45.jpg",
        description: "Illuminate your home with our Smart Wi-Fi Light Bulb. Control the brightness and color of your lights from your smartphone or voice assistant. With energy-efficient LED technology, you can create the perfect ambiance for any occasion.",
      },
      {
        id: 46,
        title: "Men's Classic Leather Wallet",
        category: "Fashion",
        price: 29.99,
        instock: true,
        img: "path/to/product46.jpg",
        description: "Organize your essentials in style with our Men's Classic Leather Wallet. Crafted from genuine leather with multiple card slots and compartments, this wallet offers both functionality and timeless elegance. Keep your cards and cash secure in style.",
      },
      {
        id: 47,
        title: "Compact Folding Pocket Knife",
        category: "Tools & Home Improvement",
        price: 24.99,
        instock: true,
        img: "path/to/product47.jpg",
        description: "Be prepared for any situation with our Compact Folding Pocket Knife. Constructed with a durable stainless steel blade and ergonomic handle, this knife is perfect for everyday carry, camping, hiking, and more. Stay sharp and ready for adventure.",
      },
      {
        id: 48,
        title: "Sports Water Bottle with Straw",
        category: "Sports & Outdoors",
        price: 14.99,
        instock: true,
        img: "path/to/product48.jpg",
        description: "Stay hydrated during your workouts with our Sports Water Bottle with Straw. Featuring a convenient flip straw and leak-proof design, this bottle is perfect for the gym, hiking, and outdoor activities. Keep pushing yourself to new heights with proper hydration.",
      },
      {
        id: 49,
        title: "Reusable Grocery Bags Set",
        category: "Home & Kitchen",
        price: 12.99,
        instock: true,
        img: "path/to/product49.jpg",
        description: "Reduce waste and save the planet with our Reusable Grocery Bags Set. Made from durable and eco-friendly materials, these bags are perfect for grocery shopping, errands, and carrying essentials. Say goodbye to single-use plastic bags for good.",
      },
      {
        id: 50,
        title: "Men's Moisture-Wicking Polo Shirt",
        category: "Fashion",
        price: 34.99,
        instock: true,
        img: "path/to/product50.jpg",
        description: "Stay cool and comfortable all day long with our Men's Moisture-Wicking Polo Shirt. Made from breathable fabric with moisture-wicking technology, this polo shirt keeps you dry and comfortable during workouts, outdoor activities, and everyday wear.",
      },
  ];
  
  export default Allproducts;
  